install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.0/hugo_0.55.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
before_script:
  - rm -rf public
script:
  - hugo
branches:
 only:
 - master
