baseURL = "https://example.com"
languageCode = "en-us"
title = "The Game Audio Club"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Archive"
    pre = "film"
    url = "/archive/"
    weight = 3
  [[menu.nav]]
    name = "Resources"
    pre = "book"
    url = "/resources/"
    weight = 4
  [[menu.nav]]
    name = "Contact"
    pre = "mail"
    url = "/contact/"
    weight = 5
  [[menu.nav]]
    name = "Live Stream"
    pre = "cast"
    url = "/stream/"
    weight = 2

[params]
  includeBootstrapJs = true
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Shoreline Game Audio Club"
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = true